//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRolesManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRole
    {
        public int Id { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Role Role { get; set; }
    }
}
